# On every push this script is executed
on: push
name: Build and deploy GH Pages via Zola
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install zola
        run: wget -q -O - "https://github.com/getzola/zola/releases/download/v0.16.0/zola-v0.16.0-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /usr/local/bin
      - name: zola build
        run: zola build
      - name: copy public folder to gh-pages
        run: |
          echo "Pushing artifacts to gh-pages"
          cd public
          git config --global init.defaultBranch main
          git config --global url."https://".insteadOf git://
          git config --global url."$GITHUB_SERVER_URL/".insteadOf "git@colinwahl":
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add .
          git commit -m "Rebuild website"
          git push --force "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/colinwahl/colinwahl.github.io.git" main:gh-pages
          echo "Deploy complete"
